name: test
channels:
  - defaults
dependencies:
  - python=3.10
  - accelerate >= 0.12.0
  - datasets >= 1.8.0
  - pytorch
  - evaluate
  - peft
  - nltk
  - py7zr
  - sentencepiece != 0.1.92
  - protobuf
  - rouge-score